#!/bin/sh /etc/rc.common

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
export HOME=/root

exec &> /var/log/mount-onedrive.log

START=99
STOP=4

start() {
        rclone mkdir /tmp/OneDrive
        rclone mount "OneDrive:/Scanned Documents/" /tmp/OneDrive/ --use-mmap --buffer-size 0 --cache-dir /tmp --vfs-cache-mode writes --vfs-cache-max-age 0s --umask 000 --allow-other --daemon
}

stop() {
        fusermount -zu /tmp/OneDrive
        rclone rmdir /tmp/OneDrive
}
